### ISSUE TITLE
Population estimates pre-2021 in mid-year-pop-est

### ISSUE THREAD

**Issue by sg-peytrignet** [kvasilopoulos/onsr#4]
Hello - I love this package but I noticed it's working differently now. It used to report time series for the dataset 'mid-year-pop-est'. How do I extract older population estimates now?

``` r
library(reprex)
library(tidyverse)
library(onsr)

pop_ons <- ons_get(id = "mid-year-pop-est") %>%
  pull(Time) %>%
  unique()
pop_ons
#> [1] 2021
```

<sup>Created on 2023-02-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kvasilopoulos** [comment]
Hi thanks for using my package.  I don't manipulate the dataset besides recognizing the type of files while reading the csv.

Maybe the edition has changed:

```
ons_desc(id = "mid-year-pop-est")
ons_get(id = "mid-year-pop-est", edition = "some-other-edition")
```
The edition ids are reported in the first function
